[package]
name = "neversea"
version = "0.0.0"
authors = [ "you",]
edition = "2018"
publish = false

[lib]
path = "src/neversea.rs"

[dependencies.dharitri-wasm]
version = "0.10.5"

[dev-dependencies.dharitri-wasm-debug]
version = "0.10.5"
